services:
    django:
        build: .
        environment:
        - DJANGO_SETTINGS_MODULE=photobooth.settings.production
        - DJANGO_DATABASE_PASSWORD
        - PHOTOBOOTH_BACKEND
        - PHOTOBOOTH_WEBDAV_URL
        - PHOTOBOOTH_WEBDAV_USERNAME
        - PHOTOBOOTH_WEBDAV_PASSWORD
        - PHOTOBOOTH_BASE_URL=http://localhost:8005/
        - PHOTOBOOTH_EVENT_NAME=Photobooth
        # GPS coordinates for EXIF data, format: "lat,lon,alt" - use https://www.latlong.net/
        - PHOTOBOOTH_GPS_COORDINATES=
        - PHOTOBOOTH_LOGO_URL=/static/img/logo.png
        - PHOTOBOOTH_ACTION_TEXT=Appuyez sur le buzzer pour prendre une photo
        - PHOTOBOOTH_COUNTDOWN_SECONDS=5
        - PHOTOBOOTH_RESULT_TIMEOUT_SECONDS=45
        - PHOTOBOOTH_SMILE_TEXT=Pensez à sourire :)
        - PHOTOBOOTH_THANKS_TEXT=Merci d'avoir utilisé ce photobooth :)
        - PHOTOBOOTH_DISMISS_TEXT=Vous pouvez également appuyer sur le buzzer si vous avez fini.
        volumes:
        - media:/srv/app/media
        ports:
        - 8005:8000
        restart: unless-stopped
    celery:
        build: .
        command: ["/srv/app/deploy/run-celery.sh"]
        environment:
        - DJANGO_SETTINGS_MODULE=photobooth.settings.production
        - DJANGO_DATABASE_PASSWORD
        - PHOTOBOOTH_BACKEND
        - PHOTOBOOTH_WEBDAV_URL
        - PHOTOBOOTH_WEBDAV_USERNAME
        - PHOTOBOOTH_WEBDAV_PASSWORD
        volumes:
        - media:/srv/app/media
        - ./ssh:/home/daemon/.ssh
        restart: unless-stopped
    rabbitmq:
        image: rabbitmq:3
        restart: unless-stopped
    postgresql:
        image: postgres:18
        environment:
            - POSTGRES_USER=photobooth_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=photobooth
        restart: unless-stopped

volumes:
  media: {}
