# Generated by Django 5.2.15 on 2026-06-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photobooth", "0003_photo_datetime_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="upload_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="photo",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
