# Generated by Django 5.2.15 on 2026-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photobooth", "0004_upload_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploading", "Uploading"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
