# Generated by Django 5.2.15 on 2026-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photobooth", "0005_upload_uploading_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="upload_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploading", "Uploading"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
